# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Geonho Bang
title: PhD Student in Autonomous Driving Research
email: ghbang@spa.hanyang.ac.kr
website: www.github.com/geonhobang

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
# github_username:  sproogen
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: geonho-3164802b1
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: itsgoingto.be
  icon: fas fa-globe
  url: https://spa.snu.ac.kr/publications
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/ghbang_profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Geonho Bang and I'm a PhD student at the SPA Lab under Professor Junwon Choi at Seoul National University. 
  My research focuses on perception systems for autonomous driving, specifically 3D object recognition using radar sensors.
  Throughout my PhD journey, I have worked on advanced radar-based perception algorithms to enhance the safety and efficiency of self-driving cars.
  I have had the opportunity to collaborate with leading automotive companies such as Hyundai Motors and HL Klemove, which has provided me with valuable industry insights and practical experience.
  My work has been recognized at prestigious conferences like CVPR and ICRA, where I have submitted several research papers.

  I am most skilled in: <mark>Autonomous Driving</mark>, <mark>Radar-based 3D Object Detection</mark>, and <mark>Machine Learning</mark>

content:
  - title: Overview
    layout: text
    content: | # this will include new lines to allow paragraphs
      Research interest areas:
      - Perception for intelligent vehicles and mobile robots
      - Knowledge Distillation for 3D object detection
      - Radar, Camera and LiDAR-based 3D object detection
      - Sensor fusion-based 3D object detection and tracking
      - Radar based point cloud generation
  
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Hanyang University, Seoul, South Korea
        sub_title: Ph.D. in Artificial Intelligence (Advisor: Prof. Jun Won Choi)
        caption: Mar 2024 - Present

    - layout: left
        title: Hanyang University, Seoul, South Korea
        sub_title: M.S. in Artificial Intelligence (Advisor: Prof. Jun Won Choi)
        caption: Mar 2022 - Feb 2024

    - layout: left
        title: Kookmin University, Seoul, South Korea
        sub_title: B.S. in Automobile and IT Convergence
        caption: Mar 2016 - Feb 2022

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: The Boring Company
        link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: Senior Network System Administrator
        caption: November 2017 - Present
        quote: >
          Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            Every company needs its networks properly administered and The Boring Compay is no exception. Digging holes is hard and I play my part making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.

  


# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
